import type { KnowledgeChunk } from "./portfolioKnowledge";

export const resumeSourceFile = "public/Dylan-Caballero-Resume.pdf";

export const resumeKnowledgeChunks: KnowledgeChunk[] = [
  {
    id: "resume-profile-summary",
    title: "Resume profile summary",
    source: "resume",
    content:
      "Dylan Caballero is a Software Engineer focused on Identity and Access Management plus AI Integration, based in Florida, USA. His resume contact details are caballerodylan96@gmail.com, github.com/Dcaba024, and portfolio-nine-coral-23.vercel.app. He is a Full Stack Software Engineer with 5+ years building secure, enterprise-scale identity and authentication systems, including 5 years engineering IAM and OAuth 2.0 infrastructure at Deloitte for a government platform serving millions of Texas residents. He combines enterprise security experience in ForgeRock IAM, OAuth 2.0, MFA, and account-lifecycle security with practical production AI agent workflows using LangChain, CrewAI, n8n, OpenAI APIs, and Claude APIs.",
    keywords: [
      "identity and access management",
      "ai integration",
      "ai automation engineer",
      "ai solutions engineer",
      "full stack software engineer",
      "florida",
      "email",
      "github",
      "portfolio",
      "deloitte",
      "iam",
      "oauth 2.0",
      "forgerock",
      "mfa",
      "enterprise software",
      "government platform",
    ],
  },
  {
    id: "resume-ai-automation-skills",
    title: "Resume AI and automation skills",
    source: "resume",
    content:
      "Dylan's resume lists AI and automation skills including n8n, OpenAI API, Claude API, LangChain, CrewAI, Agentic Workflows, Prompt Engineering, and LLM Integration. He designs end-to-end AI-powered automations using n8n workflows and LLM integrations that orchestrate API calls, process business data, and eliminate repetitive manual tasks. He builds intelligent agents capable of dynamic decision-making, multi-step reasoning, and autonomous task completion across business workflows.",
    keywords: [
      "n8n",
      "openai api",
      "claude api",
      "langchain",
      "crewai",
      "agentic workflows",
      "prompt engineering",
      "llm integration",
      "automation",
      "multi-step reasoning",
      "autonomous task completion",
    ],
  },
  {
    id: "resume-technical-skills",
    title: "Resume technical skills",
    source: "resume",
    content:
      "Dylan's resume technical stack includes Security and IAM skills such as ForgeRock IAM, OAuth 2.0, JWT, MFA, SSO, and Authentication and Authorization Architecture; AI and Automation skills such as n8n, OpenAI API, Claude API, LangChain, CrewAI, Agentic Workflows, Prompt Engineering, and LLM Integration; frontend skills including React, Next.js, Redux, TypeScript, Tailwind CSS, and Material UI; backend skills including Node.js, Express.js, Python Flask and FastAPI, Spring Boot, REST APIs, and Microservices; cloud and DevOps skills including AWS, PostgreSQL, SQL, Docker, CI/CD, GitHub Actions, and Vercel; and languages including Python, JavaScript, TypeScript, and Java.",
    keywords: [
      "security",
      "iam",
      "authentication architecture",
      "python",
      "javascript",
      "typescript",
      "java",
      "react",
      "next.js",
      "redux",
      "tailwind",
      "material ui",
      "node.js",
      "express.js",
      "flask",
      "fastapi",
      "spring boot",
      "rest api",
      "microservices",
      "forgerock",
      "oauth",
      "jwt",
      "mfa",
      "sso",
      "aws",
      "postgresql",
      "docker",
      "ci/cd",
      "github actions",
      "vercel",
    ],
  },
  {
    id: "resume-deloitte-experience",
    title: "Resume Deloitte experience",
    source: "resume",
    content:
      "Dylan worked as a Full Stack Software Engineer from November 2020 to October 2025 at Deloitte on Texas.gov and MyTexas digital platforms. He architected and led authentication, account-management, and identity workflows powering millions of Texas residents using React, TypeScript, Node.js, ForgeRock IAM, and OAuth 2.0. He integrated ForgeRock and Java-based APIs driving authentication, authorization, and the full user-account lifecycle for a high-availability government-scale platform. He delivered Google reCAPTCHA Enterprise, implemented MFA with SMS, Email, Voice, Authenticator Apps, and Security Keys, built account recovery, password management, phone verification, and MFA preference flows, engineered multi-file upload pipelines with PDF generation, validation, and backend integrations, led WCAG accessibility remediation, resolved production issues across authentication and API integrations, and partnered with architects, QA, product owners, and stakeholders.",
    keywords: [
      "deloitte",
      "full stack software engineer",
      "texas.gov",
      "mytexas",
      "authentication",
      "account management",
      "identity workflows",
      "forgerock iam",
      "oauth",
      "recaptcha enterprise",
      "mfa",
      "account recovery",
      "password management",
      "multi-file upload",
      "pdf generation",
      "wcag",
      "production issues",
      "qa",
      "stakeholders",
    ],
  },
  {
    id: "resume-babydaddy-project",
    title: "Resume BabyDaddy.com AI legal assistant project",
    source: "resume",
    content:
      "BabyDaddy.com is Dylan's AI Legal Assistant Platform at babbydaddy.vercel.app. The stack includes Next.js, TypeScript, Python, OpenAI, and LangChain. Dylan built an AI agent delivering state-specific legal guidance for custody, parenting time, and child support disputes, applying the same rigor around data handling and user-state logic used in enterprise identity systems. He designed conversational workflows that organize case timelines, build evidence checklists, and generate targeted questions for attorney meetings, with state-aware logic tailoring guidance to jurisdiction.",
    keywords: [
      "babydaddy",
      "ai legal assistant",
      "legal guidance",
      "custody",
      "parenting time",
      "child support",
      "communication disputes",
      "evidence checklists",
      "attorney meetings",
      "state-aware logic",
      "next.js",
      "python",
      "openai",
      "langchain",
      "ai agents",
    ],
  },
  {
    id: "resume-ai-resume-analyzer-project",
    title: "Resume AI Resume Analyzer SaaS project",
    source: "resume",
    content:
      "AI Resume Analyzer is Dylan's SaaS platform built with Next.js, TypeScript, Python, PostgreSQL, OpenAI, CrewAI, and LangChain. He designed multi-agent orchestration pipelines that compare resumes to job descriptions, detect skill gaps, and produce ATS optimization recommendations. He built candidate alignment scoring and actionable career-insight generation using LangChain chains and CrewAI agent roles, and delivered a full SaaS experience with authentication, database persistence, and a polished Next.js UI.",
    keywords: [
      "ai resume analyzer",
      "saas",
      "next.js",
      "typescript",
      "python",
      "postgresql",
      "openai",
      "crewai",
      "langchain",
      "multi-agent",
      "job descriptions",
      "skill gaps",
      "ats optimization",
      "candidate alignment scoring",
      "authentication",
      "database persistence",
    ],
  },
  {
    id: "resume-education-target-roles",
    title: "Resume education and target roles",
    source: "resume",
    content:
      "Dylan earned a Bachelor of Arts in Computer Science from Florida International University. His target roles are IAM Engineer, AI Solutions Engineer for enterprise and security environments, Full Stack Software Engineer focused on identity and authentication, AI Automation Engineer, Software Engineer focused on AI Integration, and Identity Security plus AI Governance roles.",
    keywords: [
      "education",
      "bachelor of arts",
      "computer science",
      "florida international university",
      "fiu",
      "target roles",
      "iam engineer",
      "ai automation engineer",
      "ai solutions engineer",
      "enterprise security",
      "full stack software engineer",
      "identity",
      "authentication",
      "ai integration",
      "identity security",
      "ai governance",
    ],
  },
];
