import type { KnowledgeChunk } from "./portfolioKnowledge";

export const resumeSourceFile = "public/Dylan-Caballero-AI-Resume.pdf";

export const resumeKnowledgeChunks: KnowledgeChunk[] = [
  {
    id: "resume-profile-summary",
    title: "Resume profile summary",
    source: "resume",
    content:
      "Dylan Caballero is an AI Automation Engineer, AI Solutions Engineer, AI Agent Developer, and Full Stack Software Engineer based in Florida, USA. His resume contact details are caballerodylan96@gmail.com, github.com/Dcaba024, and portfolio-nine-coral-23.vercel.app. He has 5+ years of experience building enterprise software, AI-powered applications, and workflow automations. He delivered secure, scalable systems at Deloitte serving millions of users and focuses on measurable business impact through intelligent automation.",
    keywords: [
      "ai automation engineer",
      "ai solutions engineer",
      "ai agent developer",
      "full stack software engineer",
      "florida",
      "email",
      "github",
      "portfolio",
      "deloitte",
      "enterprise software",
      "workflow automations",
    ],
  },
  {
    id: "resume-ai-automation-skills",
    title: "Resume AI and automation skills",
    source: "resume",
    content:
      "Dylan's resume lists AI and automation skills including n8n, OpenAI API, Claude API, LangChain, CrewAI, AI Agents, Agentic Workflows, Prompt Engineering, and LLM Integrations. He builds end-to-end AI-powered automations using n8n workflows and LLM integrations that orchestrate API calls, process business data, and eliminate repetitive manual tasks. He builds intelligent agents capable of dynamic decision-making, multi-step reasoning, and autonomous task completion across business workflows.",
    keywords: [
      "n8n",
      "openai api",
      "claude api",
      "langchain",
      "crewai",
      "ai agents",
      "agentic workflows",
      "prompt engineering",
      "llm integrations",
      "automation",
      "multi-step reasoning",
      "autonomous task completion",
    ],
  },
  {
    id: "resume-technical-skills",
    title: "Resume technical skills",
    source: "resume",
    content:
      "Dylan's resume technical stack includes Python, JavaScript, TypeScript, Java, React, Next.js, Redux, Tailwind CSS, Material UI, Node.js, Express.js, Python Flask and FastAPI, Spring Boot, REST APIs, Microservices, ForgeRock IAM, OAuth 2.0, JWT, MFA, SSO, Authentication and Authorization, AWS, PostgreSQL, SQL, Docker, CI/CD, GitHub Actions, and Vercel.",
    keywords: [
      "python",
      "javascript",
      "typescript",
      "java",
      "react",
      "next.js",
      "redux",
      "tailwind",
      "material ui",
      "node.js",
      "express.js",
      "flask",
      "fastapi",
      "spring boot",
      "rest api",
      "microservices",
      "forgerock",
      "oauth",
      "jwt",
      "mfa",
      "sso",
      "aws",
      "postgresql",
      "docker",
      "ci/cd",
      "github actions",
      "vercel",
    ],
  },
  {
    id: "resume-deloitte-experience",
    title: "Resume Deloitte experience",
    source: "resume",
    content:
      "Dylan worked as a Full Stack Software Engineer from November 2020 to October 2025 at Deloitte on Texas.gov and MyTexas digital platforms. He architected and led authentication, account-management, and identity workflows for millions of Texas residents using React, TypeScript, Node.js, ForgeRock IAM, and OAuth 2.0. He delivered Google reCAPTCHA Enterprise, implemented MFA with SMS, Email, Voice, Authenticator Apps, and Security Keys, built account recovery, password management, phone verification, and MFA preference flows, engineered multi-file upload pipelines with PDF generation and backend integrations, integrated ForgeRock and Java APIs, led WCAG compliance remediation, resolved production issues, and partnered with architects, QA, product owners, and stakeholders.",
    keywords: [
      "deloitte",
      "full stack software engineer",
      "texas.gov",
      "mytexas",
      "authentication",
      "account management",
      "identity workflows",
      "forgerock iam",
      "oauth",
      "recaptcha enterprise",
      "mfa",
      "account recovery",
      "password management",
      "multi-file upload",
      "pdf generation",
      "wcag",
      "production issues",
      "qa",
      "stakeholders",
    ],
  },
  {
    id: "resume-babydaddy-project",
    title: "Resume BabyDaddy.com AI legal assistant project",
    source: "resume",
    content:
      "BabyDaddy.com is Dylan's AI Legal Assistant Platform at babbydaddy.vercel.app. The stack includes Next.js, TypeScript, Python, OpenAI, LangChain, and AI Agents. Dylan built an AI agent that delivers state-specific legal guidance for fathers navigating custody, parenting time, child support, and communication disputes, reducing reliance on costly attorney consultations. He designed conversational workflows that organize case timelines, build evidence checklists, generate targeted questions for attorney meetings, and implemented state-aware logic to tailor legal information and next-step recommendations to the user's jurisdiction.",
    keywords: [
      "babydaddy",
      "ai legal assistant",
      "legal guidance",
      "custody",
      "parenting time",
      "child support",
      "communication disputes",
      "evidence checklists",
      "attorney meetings",
      "state-aware logic",
      "next.js",
      "python",
      "openai",
      "langchain",
      "ai agents",
    ],
  },
  {
    id: "resume-ai-resume-analyzer-project",
    title: "Resume AI Resume Analyzer SaaS project",
    source: "resume",
    content:
      "AI Resume Analyzer is Dylan's SaaS platform built with Next.js, TypeScript, Python, PostgreSQL, OpenAI, CrewAI, and LangChain. He designed multi-agent orchestration pipelines that compare resumes to job descriptions, detect skill gaps, and produce ATS optimization recommendations. He built candidate alignment scoring and actionable career-insight generation using LangChain chains and CrewAI agent roles, and delivered a full SaaS experience with authentication, database persistence, and a polished Next.js UI.",
    keywords: [
      "ai resume analyzer",
      "saas",
      "next.js",
      "typescript",
      "python",
      "postgresql",
      "openai",
      "crewai",
      "langchain",
      "multi-agent",
      "job descriptions",
      "skill gaps",
      "ats optimization",
      "candidate alignment scoring",
      "authentication",
      "database persistence",
    ],
  },
  {
    id: "resume-education-target-roles",
    title: "Resume education and target roles",
    source: "resume",
    content:
      "Dylan earned a Bachelor of Arts in Computer Science from Florida International University. His target roles are AI Automation Engineer, AI Solutions Engineer, AI Agent Engineer, Full Stack AI Engineer, Developer Advocate for AI, and IAM Engineer.",
    keywords: [
      "education",
      "bachelor of arts",
      "computer science",
      "florida international university",
      "fiu",
      "target roles",
      "ai automation engineer",
      "ai solutions engineer",
      "ai agent engineer",
      "full stack ai engineer",
      "developer advocate",
      "iam engineer",
    ],
  },
];
